package.json

As far as I can tell, `babel-plugin-rewire` isn't required as a production dependency.
At the moment I have to include the following dependencies in _my_ package.json to satisfy `babel-plugin-rewire`'s peer dependency requirements:
- `babel-core`
- `babel-template`
- `babel-types`
This pull request moves the plugin into `devDependencies`.

Move "babel-plugin-rewire" into devDependencies

---

lib/rate-limit.js

To avoid retrying when the user gives a wrong token or space id we should only retry on 500 errors

fix(ratelimit): only retry on 500

---

lib/rate-limit.js
test/unit/rate-limit-test.js

Aligns the error handling more closely to the proposed structure by axios (https://github.com/mzabriskie/axios#handling-errors)
* Restructures code to separate handling per error type
* Now catches network errors (Test disabled till https://github.com/ctimmerm/axios-mock-adapter/issues/52 is resolved)
* Real retry depending on Contentful request id (Based on a global map, not per instance. Should be fine since request id's change)

fix(error handling): applies proper axios error handling

---

lib/create-http-client.js
lib/get-user-agent.js
test/unit/user-agent-test.js

In N|Solid environments `process.release.name === 'node'` is false since the value is `nsolid`.
Since webpack checks simply for `process` to be present, I switched to this logic.

refactor(user-agent): simplify node detection

---

lib/rate-limit.js
test/unit/rate-limit-test.js

fixes #49 
My assumption when implementing connection error retries was faulty.
I assumed that errors with no config + no response are always connection errors. I checked [axios-retry](https://github.com/softonic/axios-retry/blob/master/es/index.js#L177-L180) and the new logic will now skip the retry when no config is available.
That way we match axios-retry more closely and easy up the way to migrating to the plugin later on.

fix(retry): do only retry axios related errors

---

package.json

This PR fixes the issues https://github.com/contentful/contentful.js/issues/243 without having to bundle all the modules for browser builds as done as with PR https://github.com/contentful/contentful.js/pull/247 and https://github.com/contentful/contentful-management.js/pull/171 which had the following side effect https://github.com/contentful/contentful.js/issues/260.
All this PR does is "For browser build I don't need the os package. Give me an empty one."
Please create a release tag after the merge then we can update the dependency in  https://github.com/contentful/contentful.js and https://github.com/contentful/contentful-management.js and then remove the browser field.

fix: return empty os for browser builds

---

lib/rate-limit.js

Currently, if when `setTimeout` triggers, the call of `instance(config)` throws, the thrown exception can't be caught. Separating the `delay` logic into its own function so the callback is invoked inside a `.then` means a rejected Promise is returned and can be handled, instead.

fix(rate-limit): don't throw in setTimeout cb

---

lib/create-http-client.js
lib/rate-limit.js
package.json
test/unit/rate-limit-test.js

With the new Axios beta the defaults config are no longer carried to the instance.
This behaviour is breaking the ratelimit logic

Fix ratelimit

---

lib/create-http-client.js
test/unit/create-http-client-test.js

This will need a corresponding update on the contentful.js library but lays the groundwork for setting a custom adapter.
Such as [patrickhousley/ngx-axios-adapter](https://github.com/patrickhousley/ngx-axios-adapter) to allow the usa of the contenful sdk in an angular universal situation

Allow setting a custom adapter

---

lib/create-http-client.js
test/unit/create-http-client-test.js

At Intercom, we've built a simple proxy (using NGINX) to allow our devs to access the `GET /spaces/:id/environments/:id/content_types` endpoint without needing a CMA access token.
We're using the CMA for this because it exposes validation information, which we need for our TypeScript codegen.
We have basic auth set up on the proxy server, but I was a little surprised to find that my custom `Authorization` header was being overwritten when creating the `contentful-management` client.
This is a simple change which prevents the `Authorization` header from being overwritten if it's already set. It'd be great if this could get merged and incorporated into `contentful-management` so that we could use it without forking. 😄

Do not overwrite the Authorization header

---

lib/rate-limit.js

There is a bug somewhere between our sdk-core and axios that causes agent objects to be flattened from "Agent-like objects" to regular objects on retried requests, causing an error for some enterprise users that use proxies and custom httpAgents.
I spent a day's effort trying to track down the bug, with no success. This fixes the error and retried requests eventually succeed (still using the originally configured httpAgents). I confirmed this with a test script that causes rate limit errors and a local proxy.

fix(rate-limit): do not overwrite httpAgent on retries

---

lib/create-http-client.js

This PR allows users to upload files of up to 1 GB and also allows them also to configure the maximum content length.

Add configurable max content length for Axios

---

lib/create-http-client.js
test/unit/rate-limit-test.js

See related PR https://github.com/contentful/contentful-cli/pull/175

Allow retry limit to be changed

---

lib/utils.js

fix(getNodeVersion): Safety check before accessing process.versions

---

lib/create-http-client.js
lib/rate-limit.js
package.json
test/unit/rate-limit-test.js

Originally this global map of httpclient instances -> default configs was necessary because of a bug in Axios 19.0 (The change to to SDK-core was added [here](https://github.com/contentful/contentful-sdk-core/pull/65/files)). This bug was fixed in axios, so it's no longer necessary (https://github.com/axios/axios/pull/2207). 
We suspect this may be causing a memory leak, since this memory is never released. 
Testing with the-example-app.nodejs locally, this change did improve the jsheapsize after garbage collection, so hopefully this helps our customers, too.

fix(rate-limit): do not store instances/defaultconfigs globally

---

lib/rate-limit.js

we should also call requestLogger and responseLogger in error cases, since this is one of the only way users can debug their SDK calls.

fix(loggers): call reqLogger and resLogger in error cases

---

lib/create-http-client.js
lib/create-request-config.js
lib/freeze-sys.js
lib/get-user-agent.js
lib/to-plain-object.js
package.json
rollup.config.js
test/unit/create-http-client-test.js
test/unit/mocks.js

One of the required steps to fix https://github.com/contentful/contentful.js/issues/408 by removing lodash entirely.
`cloneDeep` has been replaced by https://github.com/planttheidea/fast-copy and `isPlainObject` was made redundant by using a slightly changed `deepFreeze` implementation.

feat: remove lodash

---

.babelrc
.eslintrc.js
.prettierignore
.prettierrc
global.d.ts
lib/create-http-client.ts
lib/create-request-config.ts
lib/enforce-obj-path.ts
lib/freeze-sys.ts
lib/get-user-agent.ts
lib/index.ts
lib/rate-limit.ts
lib/to-plain-object.ts
lib/types.ts
lib/utils.ts
package.json
rollup.config.js
test/unit/create-http-client-test.js
test/unit/create-request-config-test.js
test/unit/freeze-sys-test.js
test/unit/mocks.js
test/unit/rate-limit-test.js
test/unit/user-agent-test.js
test/unit/utils-test.js

* Convert codebase to Typescript (verified in https://github.com/contentful/contentful-management.js/pull/592)
* Adds prettier and formats all code in the repository
* Adds `types` field to `package.json`

feat: add typescript types

---

src/create-http-client.ts
src/types.ts

Add support for default `maxBodyLength` in [axios request config](https://axios-http.com/docs/req_config)

feat: include maxBodyLength in axios config

---

.eslintrc.js
src/freeze-sys.ts
src/get-user-agent.ts
src/to-plain-object.ts
src/types.ts
test/unit/create-http-client-test.spec.ts
test/unit/utils-test.spec.ts

Some chore tasks:
- As we are using `eslint-config-prettier` on 8.0.0 we should update our eslint config according to this changelog: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
- Removed typescript errors or added description where I didn't see a quick solution. This should unblock local test runs.

chore(eslint): adjust eslint + unblock local test setup

---

src/get-user-agent.ts

Branched off from https://github.com/contentful/contentful-sdk-core/pull/161 and rebased.
Attends https://github.com/contentful/contentful-sdk-core/issues/120.

fix(get-user-agent): user agent platform error

---

src/get-user-agent.ts

Fix #120 - This encapsulates the `platform` from OS within that object since we use `os: false` in the package.json.
Co-authored-by: Luiz Fonseca <eu@luiz.cc>

fix(get-user-agent): user agent platform error (#191)

---

package.json
src/error-handler.ts
src/index.ts
test/unit/error-handler-test.spec.ts
test/unit/mocks.ts

Export the [error-handler library](https://github.com/contentful/contentful-management.js/blob/master/lib/error-handler.ts) in contentful-management.js from the sdk-core.

feat: export error handling function

---

package.json
src/create-http-client.ts
src/rate-limit-throttle.ts
src/rate-limit.ts
src/types.ts
test/unit/create-http-client-test.spec.ts
test/unit/rate-limit-test.spec.ts
test/unit/rate-limit-throttle.spec.ts

The max amount of CMA requests we can send per second ist defined by the customers tier (`7`, `10`, `30`).
This PR adds a client param `throttle` to set the max requests the client can sends per second. If not defined or set to `0`, nothing will be throttled.

feat(client): throttle requests

---

src/rate-limit.ts
src/types.ts
test/unit/rate-limit-test.spec.ts

The Contentful API will always return a unique request-id so using this for counting retries will not work.
Instead pass the number of attempts to the next axios calls, which also fixes a memory leak as the retry attempts object was never cleared.

fix: retry on error [ZEND-1616]

---

src/get-user-agent.ts

As a cross runtime library (browser/node), we should not rely on native modules.
The current version is not compatible with environments like remix.run. This PR fixes the issue

feat(node): remove native module dependency

---

package.json

Bump fast-copy to 2.1.3 to avoid problems in contentful.js caused by an older version: https://github.com/contentful/contentful.js/pull/1216

fix(dep): Bump fast-copy to 2.1.3

---

.contentful/vault-secrets.yaml
.github/workflows/dependabot-approve-and-request-merge.yml
package.json

Adds the vault file with the policy needed for building and deploying ecosystem packages.
Also as part of the "auto-migration" it updated the dependabot workflow.

chore: init vault [SDK-2396]

---

src/create-http-client.ts
src/utils.ts
test/unit/utils-test.spec.ts

Remove the setting of custom headers 'Accept-Encoding' and 'user-agent'. 
Previously those headers were set manually in node environments. Nowadays that should not be necessary anymore since the request library sets the header according to the environment's abilities.
Will prevent problems where e.g. browser environments were wrongly identified as node environments leading to errors like `Refused to set unsafe header "Accept-Encoding" `

fix(): remove setting customer headers [NONE]

---

src/utils.ts
test/unit/utils-test.spec.ts

Reverting https://github.com/contentful/contentful-sdk-core/pull/331/commits/2721dcf09a775f6744afdc08c9e5b3836854fe79 because the use of the function constructor will cause the `contentful.browser.min.js` bundle of `contentful.js` to be blocked by CSPs, see https://web.dev/csp/#eval-too. 
This is to unblock the usage of the bundle again, but happy about other approaches to improve the node check as was suggested here (https://github.com/contentful/contentful-sdk-core/pull/331#issuecomment-1399971519).

fix(): revert "fix(): improve isNode check" to enable csp

---

package.json
src/async-token.ts
src/create-http-client.ts
src/error-handler.ts
src/types.ts
test/unit/rate-limit-test.spec.ts

This is a major version bump of the core dependency [axios](https://axios-http.com/). It most likely introduces breaking type changes.  
**For Reference** 
- [Fix `paramsSerializer`](https://github.com/axios/axios/issues/5058)
BREAKING CHANGE: bump axios to 1.x

feat: major axios version bump to 1.x [NONE]

---

package.json
src/create-http-client.ts

We reintroduce the `paramsSerializer` (again) after removing it [here](https://github.com/contentful/contentful-sdk-core/pull/370).
This is to unblock [the axios bump in contentful-merge](https://github.com/contentful/contentful-merge/pull/462) or the skd-core bump [as such](https://github.com/contentful/contentful-merge/pull/552). We saw that tests were failing because the query set together [here](https://github.com/contentful/contentful-merge/blob/main/src/engine/create-changeset/tasks/create-fetch-partial-entities-task.ts#L43) can not properly be handled by the API anymore and instead runs into
`error: InvalidQuery: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.`
Tested locally on `contentful.js` and …

fix: re-introduce paramsSerializer

---

.circleci/config.yml
.gitignore
package-lock.json

Our 3 core packages, contentful.js, contentful-management.js and contentful-sdk-core all differ in the way they store and lock dependencies.
This is one of 3 PRs that will align that behavior:
* Migrate from yarn to npm
* Ensure lock file is committed to repository, but not included in package releases
* Ensure CircleCI uses modern, recommended way by CircleCI to install packages
* Ensure CircleCI uses the latest minor version of our minimum node version
Related PRs:
* https://github.com/contentful/contentful.js/pull/2164
* https://github.com/contentful/contentful-management.js/pull/2186

refactor: normalize package managers & CircleCI

---

package-lock.json
package.json
src/rate-limit.ts

- enables consumers of this package (CDA.js and CMA.js) to instantiate axios clients using the new `fetch` adapter that was introduced in [`axios` 1.7.0](https://github.com/axios/axios/releases/tag/v1.7.0)
- fixes a bug that was introduced with the upgrade of axios version from `1.6.8` to `1.7.x`

feat: enable 'fetch' adapter + duplicate request params fix

---

package-lock.json
package.json
src/create-http-client.ts

This reverts commit 8020f4e389f85a86ce27d24b806148bf43f68342.
URLSearchParams does not stringify nested objects

fix: Revert "feat: replace qs node API with URLSearchParams web api"

---

src/rate-limit.ts
test/unit/rate-limit-test.spec.ts

Fixes #513.
This is a draft fix intended to start the discussion.
I'm not sure if it's okay to remove the existing hack introduced in #483. Before making a decision, I’d like to learn more about the duplicate request parameters problem and how I can reproduce it in a test.
@t-col probably you could give me some hints?

fix: do not remove query parameters on retry

---

src/create-http-client.ts

Customers face issues using custom `httpsAgent`s that utilized private fields. Since these fields are not enumerable, they are not copyable, and must be excluded from the deep copy that is utilized to ensure we avoid mutating things unnecessarily.

fix: don't copy httpsAgent [EXT-5676]

---

src/error-handler.ts
test/unit/error-handler-test.spec.ts

With the use of the [extra header for cross-space resolution](https://www.contentful.com/developers/docs/references/content-delivery-api/#extra-header-for-cross-space-resolution), errors include an unobscured encoded token map. This applies the same obscuring technique used for the `Authorization` header to the `X-Contentful-Resource-Resolution` one.
Example:
```json
{
"status": 404,
"statusText": "Not Found",
"message": "The resource could not be found.",
"details": {
"type": "Space",
"id": "J2Lo0Dwdxt"
},
"request": {
"url": "https://preview.contentful.com:443/spaces/J2Lo0Dwdxt/environments/master/entries",
"headers": {
"Accept": "application/json, text/plain, */*",
"Content-Type": "application/vnd.contentful.delivery.v1+json",
"X-Contentful-Resource-Resolution": "...9fQ==", …
```

feat: obscure cross-space headers from response errors
